# permissions for end users to edit optimjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optimjob-editor-role
rules:
- apiGroups:
  - optimization.kubeflow.io
  resources:
  - optimjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimization.kubeflow.io
  resources:
  - optimjobs/status
  verbs:
  - get
