# permissions for end users to view optimjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optimjob-viewer-role
rules:
- apiGroups:
  - optimization.kubeflow.io
  resources:
  - optimjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - optimization.kubeflow.io
  resources:
  - optimjobs/status
  verbs:
  - get
